services:
  postgres:
    image: postgres:16-alpine
    container_name: task_processor_postgres
    environment:
      POSTGRES_USER: taskprocessor
      POSTGRES_PASSWORD: taskprocessor
      POSTGRES_DB: taskprocessor
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U taskprocessor']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: task_processor_redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-server
    container_name: task_processor_server
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://taskprocessor:taskprocessor@postgres:5432/taskprocessor
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
      LOG_LEVEL: info

    ports:
      - "3000:3000"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-worker
    depends_on:
      - postgres
      - redis
      - server
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://taskprocessor:taskprocessor@postgres:5432/taskprocessor
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
      LOG_LEVEL: info
    deploy:
      replicas: 2
      resources:
            limits:
              memory: 100M
              cpus: '0.50'
            reservations:
              memory: 64M

    restart: unless-stopped
volumes:
  postgres_data:
  redis_data:
